---
pipeline_key: ba_lineitem_adnetwork_configs
pipeline_type: mysql_redshift
incremental_sync: True

mysql:
  conn_id: buzzad_mysql
  table_name: lineitem_adnetwork_configs
  fields:
  - id
  - lineitem_id
  - report_app_id
  - report_placement_id
  increment_key: id
  increment_key_type: dump
  unique_key_list:
  - id

redshift:
  table_name: ba_lineitem_adnetwork_configs
  fields:
  - id
  - lineitem_id
  - report_app_id
  - report_placement_id
  copy_method: replace
  create_table_syntax: |
    CREATE TABLE IF NOT EXISTS {table_name}
    (
      id                        INT8            NOT NULL       ENCODE AZ64,
      lineitem_id               INT8            NOT NULL       ENCODE AZ64,
      report_app_id             VARCHAR(256)    DEFAULT NULL   ENCODE ZSTD,
      report_placement_id       VARCHAR(256)    DEFAULT NULL   ENCODE ZSTD
    )
    DISTSTYLE ALL
    SORTKEY(id)
    ;
  increment_key: id
  increment_key_type: dump
  unique_key_list:
  - id
