---
pipeline_key: pointsvc_app_config
pipeline_type: mysql_redshift
incremental_sync: True

mysql:
  conn_id: pointsvc_mysql
  table_name: point_app_config
  fields:
  - id
  - app_id
  - auto_redeem
  - min_redeem_amount
  - point_rate
  - created_at
  - updated_at
  increment_key: updated_at
  increment_key_type: timestamp
  unique_key_list:
  - id
redshift:
  table_name: pointsvc_app_config
  fields:
  - id
  - app_id
  - auto_redeem
  - min_redeem_amount
  - point_rate
  - created_at
  - updated_at
  copy_method: upsert
  create_table_syntax: |
    CREATE TABLE IF NOT EXISTS {table_name}
    (
      id                BIGINT    NOT NULL  ENCODE AZ64,
      app_id            BIGINT    NOT NULL  ENCODE AZ64,
      auto_redeem       INT2      NOT NULL  ENCODE AZ64,
      min_redeem_amount INT       NOT NULL  ENCODE AZ64,
      point_rate        INT       NOT NULL  ENCODE AZ64,
      created_at        TIMESTAMP NOT NULL  ENCODE AZ64,
      updated_at        TIMESTAMP NOT NULL  ENCODE AZ64
    )
    DISTKEY(app_id)
    SORTKEY(created_at)
    ;
  increment_key: updated_at
  increment_key_type: timestamp
  unique_key_list:
  - id
