# CREATE TABLE `point_app_config` (
#   `id` int(11) NOT NULL AUTO_INCREMENT,
#   `app_id` bigint(20) NOT NULL,
#   `auto_redeem` tinyint(1) NOT NULL DEFAULT '1',
#   `min_redeem_amount` int(11) NOT NULL DEFAULT '1',
#   `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
#   `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
#   `point_rate` int(11) NOT NULL DEFAULT '1',
#   PRIMARY KEY (`id`),
#   UNIQUE KEY `app_id` (`app_id`)
# ) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
---
pipeline_key: pointsvc_ls_point_app_config
pipeline_type: mysql_unload_s3
pipeline_dag_configs:
  start_date: 2020-09-16 17:00:00
  schedule_interval: "0 17 * * *"

mysql:
  conn_id: pointsvc_mysql
  table_name: point_app_config
  fields:
  - id
  - app_id
  - auto_redeem
  - min_redeem_amount
  - created_at
  - updated_at
  - point_rate
  increment_key: id
  increment_key_type: dump

s3:
  bucket: "{{ var.value.get('server_env', 'prod') }}-buzzvil-data-lake"
  prefix: pointsvc/landing_snapshot/point_app_config/year={year}/month={month}/day={day}/hour={hour}
  file_key: pointsvc_ls_point_app_config
  data_format: parquet

athena:
  create_table_syntax: |
    CREATE EXTERNAL TABLE IF NOT EXISTS {database}.{table}(
      id                  BIGINT,
      app_id              BIGINT,
      auto_redeem         BIGINT,
      min_redeem_amount   BIGINT,
      created_at          TIMESTAMP,
      updated_at          TIMESTAMP,
      point_rate          BIGINT
    )
    PARTITIONED BY (partition_timestamp timestamp)
    STORED AS PARQUET
    LOCATION '{location}'
    TBLPROPERTIES("parquet.compress"="SNAPPY");
  database: "{{ var.value.get('server_env', 'prod') }}_pointsvc"
  table: ls_point_app_config
  location: "s3://{{ var.value.get('server_env', 'prod') }}-buzzvil-data-lake/pointsvc/landing_snapshot/point_app_config"
  partition:
    key: partition_timestamp
    value: "{{execution_date.strftime('%Y-%m-%d %H:00:00')}}"
    subdir: "year={{ execution_date.strftime('%Y') }}/month={{ execution_date.strftime('%m') }}/day={{ execution_date.strftime('%d') }}/hour={{ execution_date.strftime('%H') }}"
